Repository ml4ai/delphi, pull requests merged in 2019-03, with the labels that each got.

#196 Removing necessity for List wrapping
  delphi/translators/for2py/scripts/genCode.py
  delphi/translators/for2py/scripts/genPGM.py
Labels: enhancement

#215 For2py refactoring to remove mutable global variables and increase referential transparency
  delphi/translators/for2py/genPGM.py
Labels: enhancement

#218 Switching to Codecov
  .travis.yml
  setup.py
Labels: enhancement

#224 For2Py custom exception class
  delphi/translators/for2py/__init__.py
  delphi/translators/for2py/arrays.py
  delphi/translators/for2py/format.py
  delphi/translators/for2py/genCode.py
  delphi/translators/for2py/genPGM.py
  delphi/translators/for2py/pyTranslate.py
Labels: enhancement

#225 GenSyms, namespaces, etc.
  delphi/translators/for2py/autoTranslate
  delphi/translators/for2py/genPGM.py
  delphi/translators/for2py/mod_index_generator.py
  delphi/translators/for2py/pyTranslate.py
  delphi/translators/for2py/translate.py
  tests/data/PETASCE_single.for
  tests/data/PETASCE_single.json
  tests/data/PETPT.json
  tests/data/crop_yield.f
  tests/data/crop_yield.json
  tests/data/io-tests/iotest_05_grfn.json
  tests/test_program_analysis.py
Labels: enhancement

#226 Documentation and API updates
  .gitignore
  .travis.yml
  README.md
  delphi/AnalysisGraph.py
  delphi/__init__.py
  delphi/export.py
  delphi/translators/__init__.py
  delphi/translators/for2py/pyTranslate.py
  delphi/visualization.py
  docs/AnalysisGraph_API.rst
  docs/CONTRIBUTING.md
  docs/conf.py
  docs/delphi.icm_api.rst
  docs/delphi.rst
  docs/delphi.translators.for2py.rst
  docs/delphi.translators.rst
  docs/delphi_logo.png
  docs/for2py_API.rst
  docs/index.rst
  docs/installation.md
  docs/make_figures.py
  docs/usage.md
  setup.py
  tests/test_program_analysis.py
Labels: enhancement

#227 Bugfix for pyTranslate.py
  delphi/translators/for2py/pyTranslate.py
Labels: bugfix

#230 Provenance from text reading added to variable nodes in CodeExplorer
  delphi/GrFN/networks.py
  delphi/apps/CodeExplorer/app.py
  delphi/apps/CodeExplorer/templates/cyjs.js
  tests/test_analysis.py
Labels: enhancement

#233 FIBs are now wired and runnable
  delphi/GrFN/networks.py
  delphi/translators/for2py/genPGM.py
  tests/test_GrFN.py
  tests/test_analysis.py
Labels: bugfix, enhancement
