Repository ml4ai/delphi, pull requests merged in 2019-09, with the labels that each got.

#345 Removing SIR*_lambdas.py and SIR*.json files to prevent Travis CI errors
  delphi/translators/GrFN2WiringDiagram/SIR-Gillespie-SD__alt_lambdas.py
  delphi/translators/GrFN2WiringDiagram/SIR-simple_lambdas.py
  tests/data/program_analysis/SIR-Gillespie-MS.json
  tests/data/program_analysis/SIR-Gillespie-MS_GrFN.json
  tests/data/program_analysis/SIR-Gillespie-MS_lambdas.py
  tests/data/program_analysis/SIR-Gillespie-SD_inline.json
  tests/data/program_analysis/SIR-Gillespie-SD_inline_GrFN.json
  tests/data/program_analysis/SIR-Gillespie-SD_inline_lambdas.py
  tests/data/program_analysis/SIR-simple.json
  tests/data/program_analysis/SIR-simple_lambdas.py
Labels: bugfix

#344 CORRECTED PA/MA Pipeline Update and GrFN2WD Translation
  delphi/GrFN/networks.py
  delphi/GrFN/utils.py
  delphi/apps/CodeExplorer/app.py
  delphi/apps/CodeExplorer/templates/index.html
  delphi/translators/GrFN2WiringDiagram/SIR-Gillespie-SD__alt.f
  delphi/translators/GrFN2WiringDiagram/SIR-simple.f
  delphi/translators/GrFN2WiringDiagram/SIR-simple__functions.jl
  delphi/translators/GrFN2WiringDiagram/SIR-simple__wiring.jl
  delphi/translators/GrFN2WiringDiagram/example_GrFN2WD_translation.ipynb
  delphi/translators/GrFN2WiringDiagram/translate.py
  delphi/translators/for2py/f2grfn.py
  delphi/translators/for2py/genCode.py
  delphi/translators/for2py/genPGM.py
  delphi/translators/for2py/preprocessor.py
  delphi/translators/for2py/pyTranslate.py
  delphi/translators/for2py/rectify.py
  delphi/translators/for2py/syntax.py
  delphi/translators/for2py/types_ext.py
  tests/aske/test_GrFN.py
  tests/aske/test_analysis.py
  tests/aske/test_program_analysis.py
  tests/aske/test_webapp.py
  tests/data/GrFN/petpt_cag_edges.txt
  tests/data/GrFN/petpt_grfn_edges.txt
  tests/data/program_analysis/PETASCE_markedup.py
  tests/data/program_analysis/PETASCE_single.json
  tests/data/program_analysis/PETASCE_single.py
  tests/data/program_analysis/PETPT.py
  tests/data/program_analysis/PETPT_GrFN.json
  tests/data/program_analysis/SIR-Gillespie-MS.f
  tests/data/program_analysis/SIR-Gillespie-SD_inline.f
  tests/data/program_analysis/SIR-Gillespie-SD_inline.py
  tests/data/program_analysis/SIR-simple.f
  tests/data/program_analysis/arrays-basic-06.py
  tests/data/program_analysis/continuation_line/continuation-lines-01.py
  tests/data/program_analysis/continuation_line/continuation-lines-02.py
  tests/data/program_analysis/crop_yield.py
  tests/data/program_analysis/crop_yield_GrFN.json
  tests/data/program_analysis/cycle/cycle_03.py
  tests/data/program_analysis/derived-types-04.py
  tests/data/program_analysis/derived-types/derived-types-03.py
  tests/data/program_analysis/do-while/do_while_04.py
  tests/data/program_analysis/goto/goto_02.py
  tests/data/program_analysis/goto/goto_09.py
  tests/data/program_analysis/io-tests/iotest_05.py
  tests/data/program_analysis/io-tests/iotest_05_GrFN.json
  tests/data/program_analysis/io-tests/iotest_06.py
  tests/data/program_analysis/io-tests/iotest_07.py
  tests/data/program_analysis/modules/m_mymod8.py
  tests/data/program_analysis/modules/test_module_08.py
  tests/data/program_analysis/save/simple_variables/save-02.py
Labels: bugfix, enhancement

#346 Updating link to Arizona_Text_to_Model_Procedure.pdf
  README.md
Labels: enhancement

#348 SIR Demo Link Tables
  delphi/GrFN/linking.py
  delphi/GrFN/networks.py
  tests/aske/test_GrFN.py
  tests/data/program_analysis/SIR-Gillespie-SD_GrFN_with_groundings.json
Labels: enhancement

#366 Running Travis testing with docker
  .travis.yml
  CMakeLists.txt
  Dockerfile
  delphi/apps/CodeExplorer/Dockerfile
  delphi/apps/CodeExplorer/cyjs.py
  delphi/translators/for2py/f2grfn.py
  docker-build.sh
  docs/Makefile
  external/range-v3/include/range/v3/view/unbounded 2.hpp
  external/range-v3/include/range/v3/view_facade 2.hpp
  external/range-v3/perf/CMakeLists 2.txt
  external/range-v3/test/CMakeLists 2.txt
  external/range-v3/test/action/adjacent_remove_if 2.cpp
  external/range-v3/test/action/cont_concepts 2.cpp
  external/range-v3/test/action/drop_while 2.cpp
  external/range-v3/test/action/remove_if 2.cpp
  external/range-v3/test/algorithm/is_heap1 2.cpp
  external/range-v3/test/algorithm/is_heap_until2 2.cpp
  external/range-v3/test/algorithm/set_difference1 2.cpp
  external/range-v3/test/algorithm/set_difference3 2.cpp
  external/range-v3/test/algorithm/set_intersection1 2.cpp
  external/range-v3/test/algorithm/set_intersection4 2.cpp
  external/range-v3/test/algorithm/set_intersection6 2.cpp
  external/range-v3/test/algorithm/set_symmetric_difference3 2.cpp
  external/range-v3/test/algorithm/set_symmetric_difference5 2.cpp
  external/range-v3/test/iterator/CMakeLists 2.txt
  external/range-v3/test/iterator/diffmax_t 2.cpp
  external/range-v3/test/view/all 2.cpp
  external/range-v3/test/view/delimit 2.cpp
  external/range-v3/test/view/remove 2.cpp
  external/range-v3/test/view/repeat 2.cpp
  external/range-v3/test/view/take_last 2.cpp
  external/range-v3/test/view/tokenize 2.cpp
  external/range-v3/test/view/view 2.cpp
  external/range-v3/test_package/conanfile 2.py
  tests/wm/test_rest_api.py
Labels: bug, enhancement
